{% set version = '0.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-minty
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/minty_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/minty/minty_{{ version }}.tar.gz
  sha256: cfbdc6603c8fb54ea4d43091e2aee4c99212e6e20a335ed89576156d86237acd

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cpp11
    - r-tzdb
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cpp11
    - r-tzdb

test:
  commands:
    - $R -e "library('minty')"           # [not win]
    - "\"%R%\" -e \"library('minty')\""  # [win]

about:
  home: https://gesistsa.github.io/minty/, https://github.com/gesistsa/minty
  license: MIT
  summary: Port the type guesser from 'readr' (so-called 'readr' first edition parsing engine,
    now superseded by 'vroom').
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
